version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - ai-agents-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - ai-agents-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_agents
    ports:
      - "5432:5432"
    networks:
      - ai-agents-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ai-agents-network

networks:
  ai-agents-network:

volumes:
  postgres_data:
