FROM node:18-alpine

WORKDIR /app

# Установка зависимостей
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci

# Копирование исходного кода
COPY frontend/ .

# Сборка приложения
RUN npm run build

# Запуск приложения
CMD ["npm", "start"]
